### PR TITLE
updated README.md to add a creative implementation by Akshay Bahadur

### PR DESCRIPTION
**Pull request by akshaybahadur21**
I have added my implementation which you could check at 
https://github.com/akshaybahadur21/QuickDraw
My website : http://akshaybahadur.com/
LinkedIn : https://www.linkedin.com/in/akshaybahadur21/

### CODE REVIEW

**Comment by akshaybahadur21** [comment]
@googlebot - I have signed
@HalfdanJ - can you please check.

**Comment by HalfdanJ** [comment]
Thanks a lot! Correct me if you think I'm wrong, but I think it would make more sense to categorize this under code and tools?

**Comment by akshaybahadur21** [comment]
@HalfdanJ - Oh yes. That made sense. I have made the change, can you check.

**Comment by HalfdanJ** [comment]
Thanks

**Comment by najeebulhussan** [comment]
done

**Comment by azhar123123** [comment]
@googlebot - I have signed
@HalfdanJ - can you please check.

**Pull request merged**
